name: Update sites.md

on:
  push:
    branches:
      - sites.yaml
      

permissions:
  contents: write

jobs:
  update-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files (debug)
        run: ls -R

      - name: List .github/scripts files (debug)
        run: ls -l .github/scripts || echo "Folder not found"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate sites.md
        run: python .github/scripts/generate_sites_md.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}

          git add sites.md
          git commit -m "Update sites.md" || echo "No changes to commit"
          git push origin HEAD
