name: Update sites.md

on:
  push:
    branches:
      - main
    paths:
      - 'sites.yaml'
      - 'scripts/generate_sites_md.py'
      - '.github/workflows/update-sites-md.yml'

permissions:
  contents: write  # <-- This allows the workflow to push

jobs:
  update-sites-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate sites.md
        run: python scripts/generate_sites_md.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ARASH }}
        run: |
          git config --global user.name "Arash Khajavi"
          git config --global user.email "Arash-Khajavi@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${ARASH}@github.com/${{ github.repository }}
          git add sites.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update sites.md"
          git pull --rebase origin main
          git push origin HEAD
