name: Update sites.md

on:
  push:
    paths:
      - sites.yaml

jobs:
  update-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate sites.md
        run: python .github/scripts/generate_sites_md.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Set remote URL with access token
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          
          # Show remote to verify token is being used
