name: Update sites.md

on:
  push:
    paths:
      - 'sites.yaml'
      - '.github/workflows/update-sites-md.yml'
      - 'scripts/generate_sites_md.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate sites.md
        run: python scripts/generate_sites_md.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sites.md
          git commit -m "Update sites.md" || echo "No changes to commit"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

