name: Update sites.md

on:
  push:
    branches:
      - main
    paths:
      - 'sites.yaml'
      - 'scripts/generate_sites_md.py'
      # - '.github/workflows/update-sites-md.yml' # Optional

jobs:
  update-sites-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Consider pinning to a full version or SHA

      - name: Set up Python
        uses: actions/setup-python@v4 # Consider pinning

      - name: Install dependencies
        run: pip install pyyaml # Or use requirements.txt for more packages

      - name: Generate sites.md
        run: python scripts/generate_sites_md.py

      - name: Commit and push changes
        env:
          ARASH: ${{ secrets.ARASH }}
        run: |
          git config --global user.name "Arash Khajavi"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${ARASH}@github.com/${{ github.repository }}
          git add sites.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update sites.md"
          git pull --rebase origin main
          git push origin HEAD
