name: Update sites.md

on:
  push:
    branches:
      - main  # 👈 Ensure this matches your branch name!
    paths:
      - 'sites.yaml'
      - '.github/workflows/update-sites-md.yml'
      - 'scripts/generate_sites_md.py'

jobs:
  update-sites-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate sites.md
        run: python scripts/generate_sites_md.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ARASH }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${ARASH}@github.com/${{ github.repository }}
          git add sites.md
          git diff --cached --quiet || git commit -m "Update sites.md"
          git push origin HEAD


